### PR TITLE
Update project for SDK 3.0

### PR DESCRIPTION
**Pull request by C-D-Lewis**
Ping @cjwilliams for review.

### CODE REVIEW

**Comment by cjwilliams** [comment]
Update looks fine and builds, :+1: 

However, our getting started tutorial page seems to be out of date as the end screenshot looks like this:
image

And the screenshot I took looks like this:
image

We should also check to make sure the gists associated with the tutorial still compile (though based on the changes in this PR, I expect they do)

**Comment by C-D-Lewis** [comment]
This project is the result of part 3, which has a screenshot looking like this:



I will check the gists.

**Comment by C-D-Lewis** [comment]
The gists appear to be fine!

**Comment by tyhoff** [comment]
ping. Ran into this not being updated.

**Comment by C-D-Lewis** [comment]
Verified this works on both platforms.

**Pull request merged**
